"""Add Admin + relationship

Revision ID: 2c21c6a91742
Revises: 5e063ddbcac1
Create Date: 2025-07-26 15:22:10.547722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c21c6a91742'
down_revision = '5e063ddbcac1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visitor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo', sa.String(length=200), nullable=True))
        batch_op.drop_column('image_filename')
        batch_op.drop_column('status')
        batch_op.drop_column('purpose')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visitor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('purpose', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('image_filename', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
        batch_op.drop_column('photo')

    # ### end Alembic commands ###
